name: "Test"
on: [push, pull_request]

jobs:
  test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: 'minetest/minetest_game'
        path: minetest_game

    - name: Run tests
      run: ./.util/run_tests.sh --docker
